name: Desi Distraction
favicon: null
layout_spectrum: 0.7119909687899053
typography_spectrum: 0.4734631010796875
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.5450153858400881
  lightness: 0.16237784479744732
  saturation: 0.11658936669118702
  rhythmicContrast: 0.25951728876680136
purpose: []
