name: Desi Distraction
favicon: null
layout_spectrum: 0.7119909687899053
typography_spectrum: 0.4734631010796875
title: Desi Distraction
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#350090'
    - '#fcfaff'
    - '#af006f'
    - '#029570'
    - '#656dd2'
  brandStrength: 0.5
  lightness: 0.125
  saturation: 0.1875
  rhythmicContrast: 0.25
purpose: []
